operator_manifest_to_bundle_dir: /tmp/operator-test/operator-manifest-to-bundle
# operator_name: ""
operator_version: latest
opm_container_tool: "docker"
bundle_image_namespace: test-operator
bundle_registry: localhost:5000